local c = require("semimono.colors")

local M = {}

M.native = {
	Normal = { fg = c.fg, bg = c.bg },
	NormalNC = { fg = c.fg, bg = c.bg },
	SignColumn = { fg = c.fg, bg = c.bg },
	EndOfBuffer = { fg = c.gray03 },
	NormalFloat = { fg = c.fg, bg = c.gray02 },
	FloatBorder = { fg = c.blue, bg = c.gray02 },
	ColorColumn = { fg = c.none, bg = c.gray01 },
	Conceal = { fg = c.gray05 },
	Cursor = { fg = c.cyan, bg = c.none, reverse = true },
	CursorIM = { fg = c.cyan, bg = c.none, reverse = true },
	Directory = { fg = c.blue, bg = c.none, bold = true },
	DiffAdd = { fg = c.bright_green, bg = c.none, reverse = true },
	DiffChange = { fg = c.bright_blue, bg = c.none, reverse = true },
	DiffDelete = { fg = c.bright_red, bg = c.none, reverse = true },
	DiffText = { fg = c.fg, bg = c.none, reverse = true },
	ErrorMsg = { fg = c.red },
	Folded = { fg = c.gray05, bg = c.none, italic = true },
	FoldColumn = { fg = c.blue },
	IncSearch = { reverse = true },
	LineNr = { fg = c.gray05 },
	CursorLineNr = { fg = c.gray07 },
	MatchParen = { fg = c.yellow, bold = true },
	ModeMsg = { fg = c.cyan, bold = true },
	MoreMsg = { fg = c.cyan, bold = true },
	NonText = { fg = c.gray03 },
	Pmenu = { fg = c.gray07, bg = c.gray02 },
	PmenuSel = { fg = c.bg, bg = c.gray06 },
	PmenuSbar = { fg = c.fg, bg = c.gray02 },
	PmenuThumb = { fg = c.fg, bg = c.gray05 },
	Question = { fg = c.green, bold = true },
	QuickFixLine = { fg = c.blue, bg = c.gray01, bold = true, italic = true },
	qfLineNr = { fg = c.blue, bg = c.gray01 },
	Search = { reverse = true },
	SpecialKey = { fg = c.gray03 },
	SpellBad = { fg = c.red, bg = c.none, italic = true, undercurl = true },
	SpellCap = { fg = c.blue, bg = c.none, italic = true, undercurl = true },
	SpellLocal = { fg = c.cyan, bg = c.none, italic = true, undercurl = true },
	SpellRare = { fg = c.cyan, bg = c.none, italic = true, undercurl = true },
	StatusLine = { fg = c.gray07, bg = c.gray01 },
	StatusLineNC = { fg = c.gray06, bg = c.gray01 },
	StatusLineTerm = { fg = c.gray07, bg = c.gray01 },
	StatusLineTermNC = { fg = c.gray07, bg = c.gray01 },
	TabLineFill = { fg = c.gray05, bg = c.gray01 },
	TablineSel = { fg = c.bg, bg = c.gray07 },
	Tabline = { fg = c.gray05 },
	Title = { fg = c.cyan, bg = c.none, bold = true },
	Visual = { fg = c.none, bg = c.gray03 },
	VisualNOS = { fg = c.none, bg = c.gray03 },
	WarningMsg = { fg = c.yellow, bold = true },
	WildMenu = { fg = c.bg, bg = c.blue, bold = true },
	CursorColumn = { fg = c.none, bg = c.gray02 },
	CursorLine = { fg = c.none, bg = c.gray01 },
	ToolbarLine = { fg = c.fg, bg = c.gray01 },
	ToolbarButton = { fg = c.fg, bg = c.none, bold = true },
	NormalMode = { fg = c.cyan, bg = c.none, reverse = true },
	InsertMode = { fg = c.green, bg = c.none, reverse = true },
	VisualMode = { fg = c.cyan, bg = c.none, reverse = true },
	VertSplit = { fg = c.gray02 },
	CommandMode = { fg = c.gray05, bg = c.none, reverse = true },
	Warnings = { fg = c.yellow },
	healthError = { fg = c.red },
	healthSuccess = { fg = c.green },
	healthWarning = { fg = c.yellow },

	-- Common
	Type = { fg = c.cyan },
    StorageClass = { fg = c.cyan },
    Structure = { fg = c.fg },
    Constant = { fg = c.purple },
    Comment = { fg = c.darkGreen, bg = c.none },
    Conditional = { fg = c.blue, bg = c.none },
    Keyword = { fg = c.blue, bg = c.none },
    Repeat = { fg = c.blue, bg = c.none },
    Boolean = { fg = c.purple, bg = c.none },
    Function = { fg = c.blue, bg = c.none },
    Identifier = { fg = c.blue, bg = c.none },
    String = { fg = c.green, bg = c.none },
    Character = { fg = c.green },
    Number = { fg = c.purple },
    Float = { fg = c.purple },
    Statement = { fg = c.blue },
    Label = { fg = c.cyan },
    Operator = { fg = c.yellow },
    Exception = { fg = c.yellow },
    PreProc = { fg = c.red },
    Include = { fg = c.blue },
    Define = { fg = c.cyan },
    Macro = { fg = c.blue },
    Typedef = { fg = c.cyan },
    PreCondit = { fg = c.cyan },
    Special = { fg = c.blue, bg = c.none },
    SpecialChar = { fg = c.cyan },
    Tag = { fg = c.yellow },
    Delimiter = { fg = c.gray07 },
    SpecialComment = { fg = c.blue },
    Debug = { fg = c.red },
    Underlined = { fg = c.cyan, bg = c.none },
    Ignore = { fg = c.gray07 },
    Error = { fg = c.red, bg = c.none },
    Todo = { fg = c.cyan, bg = c.none },
}

M.html = {
	htmlArg = { fg = c.fg },
    htmlBold = { fg = c.fg, bg = c.none },
    htmlEndTag = { fg = c.fg },
    htmlStyle = { fg = c.blue, bg = c.none },
    htmlLink = { fg = c.green },
    htmlSpecialChar = { fg = c.yellow },
    htmlSpecialTagName = { fg = c.blue },
    htmlTag = { fg = c.fg },
    htmlTagN = { fg = c.yellow },
    htmlTagName = { fg = c.yellow },
    htmlTitle = { fg = c.green },
    htmlH1 = { fg = c.blue },
    htmlH2 = { fg = c.blue },
    htmlH3 = { fg = c.blue },
    htmlH4 = { fg = c.blue },
    htmlH5 = { fg = c.blue },
}

M.terminal = {
	terminal_color_0 = c.black,
	terminal_color_1 = c.red,
	terminal_color_2 = c.green,
	terminal_color_3 = c.yellow,
	terminal_color_4 = c.blue,
	terminal_color_5 = c.magenta,
	terminal_color_6 = c.cyan,
	terminal_color_7 = c.white,
	terminal_color_8 = c.bright_black,
	terminal_color_9 = c.bright_red,
	terminal_color_10 = c.bright_green,
	terminal_color_11 = c.bright_yellow,
	terminal_color_12 = c.bright_blue,
	terminal_color_13 = c.bright_magenta,
	terminal_color_14 = c.bright_cyan,
	terminal_color_15 = c.bright_white,
	terminal_color_background = c.bg,
	terminal_color_foreground = c.fg,
}

return M
